# Generated by Django 2.2.11 on 2020-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_add_team_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lastsuccess',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
