# Generated by Django 3.2.16 on 2024-03-19 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0006_blog_lastsuccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('feed', models.ForeignKey(db_column='feed', on_delete=django.db.models.deletion.CASCADE, to='register.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Moderator notes',
                'db_table': 'moderatornotes',
                'ordering': ['-ts'],
            },
        ),
    ]
