# Generated by Django 5.2.10 on 2026-04-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_require_team_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postedto',
            field=models.JSONField(null=False, blank=True, default=dict),
        ),
        migrations.RunSQL(
            "UPDATE posts SET postedto=jsonb_build_object('twitter', true) WHERE twittered",
            "UPDATE posts  SET twittered = true WHERE postedto ? 'twitter''",
        ),
        migrations.RemoveField(
            model_name='post',
            name='twittered',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='twitteruser',
        ),
        migrations.RunSQL(
            "ALTER TABLE posts DROP COLUMN IF EXISTS tweetid",
            "ALTER TABLE posts ADD COLUMN tweetid int8 NULL",
        )
    ]
